#!/bin/bash

# ciclo for per prendere tutti i file doc e trasformarli in docx

for i in `find /home/simel/hobbyfarm/progetto_sql_indirizzi/$1 -type f -name "*.doc"`
do
echo $i
libreoffice --headless --convert-to docx --outdir /home/simel/hobbyfarm/progetto_sql_indirizzi/$2 $i
done
